### ISSUE TITLE
Futures timed out

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#100]
Sometimes I get an error when I use FREME NER. When I do the same request again it works. The problem does not occur often but I see it again and again. The API call that produced the issue is

http://api.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&informat=text/html&outformat=turtle&input=Bob%20Johnston%2C%20The%20Gutter%20Bookshop%2C%20Temple%20Bar%3Cbr%20%2F%3E%3Cbr%20%2F%3E%E2%80%9CA%20wonderful%20journey%20through%20Joyce%27s%20epic%20novel

here is [error.txt](https://github.com/freme-project/freme-ner/files/256609/error.txt) from freme-ner. I think the origin of the problem is shown in this part of the log:

```
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:116)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:116)
	at org.elinker.core.api.scala.FremeNer.spotLinkClassify(FremeNer.scala:73)
	at org.elinker.core.api.java.FremeNer.spotLinkClassify(FremeNer.java:55)
	at org.elinker.core.api.java.FremeNer$$FastClassBySpringCGLIB$$9f471e1f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649)
``` 

Any idea why this happens?

**Comment by jnehring** [comment]
This bug seems to be important to me. It happens a lot and makes (I estimate) 1 out of 3 API calls fail. We should start this issue next when the current bugfixes of FREME NER are finished.

**Comment by m1ci** [comment]
is this happening when you submit concurrent requests or sequential requests?

**Comment by jnehring** [comment]
> is this happening when you submit concurrent requests or sequential requests?

both. but lately I did not come across this error.

**Comment by sandroacoelho** [comment]
I've tested locally and increasing the timeouts  in the Await.result calls in FremeNer.scala appears to make these go away. It also alleviates this issue. I will change it on the server and then we can test it

**Comment by m1ci** [comment]
@sandroacoelho did you manage to do the changes at the server and test if this solves the issue?

**Comment by sandroacoelho** [comment]
Hi all,
I have tested after increasing timeout and not found the problems anymore. So, I am closing this issue.
If the bugs persist, I will reopen it and add stress test
Thanks,

**Comment by jnehring** [comment]
I used the FREME workflow editor, loaded the HTML 5 example and used e-Entity. In the UI get the "Undeclared throwable exception", on freme worker I see this log message:

```
ERROR   2016-07-25 09:38:36,419 [http-nio-7002-exec-4] eu.freme.common.exception.ExceptionHandlerService  - Request: http://rv2622.1blu.de:7002/e-entity/freme-ner/documents raised
java.lang.reflect.UndeclaredThrowableException
        at org.elinker.core.api.java.FremeNer$$EnhancerBySpringCGLIB$$b761bb81.spotLinkClassify(<generated>)
        at org.elinker.core.rest.FremeNerEnrichment.execute(FremeNerEnrichment.java:198)
        at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
...
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:116)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
        at scala.concurrent.Await$.result(package.scala:116)
        at org.elinker.core.api.scala.FremeNer.spotLinkClassify(FremeNer.scala:80)
        at org.elinker.core.api.java.FremeNer.spotLinkClassify(FremeNer.java:51)
        at org.elinker.core.api.java.FremeNer$$FastClassBySpringCGLIB$$9f471e1f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649)
        ... 82 more
 ``` 

In parallel I am trying out the scripts from #114 so maybe there is a heavy load on the server and therefore the conection timed out?

Maybe you can create a better error message? This means that when the connection times out you return a proper exception to the user?

When you throw an exception like [this](https://github.com/freme-project/FREMECommon/blob/master/src/main/java/eu/freme/common/exception/BadRequestException.java) then you can set the response status to 500 (internal server error) and the reason (error message) to "The connection to the SOLR server timed out Please try again later". The error message and the response status will be send to the client.

**Comment by sandroacoelho** [comment]
Hi @jnehring 

Who cuts the communication and sends a 500 (internal server error)  are the [Akka actors](https://github.com/freme-project/freme-ner/blob/7fcbd39c016264c2fb2872164cac63485beaa68c/src/main/scala/org/elinker/core/api/scala/FremeNer.scala#L30).  I believe that Solr, even when it is very busy would answer the request.

Would you mind if I change it to an external parameter and recommend to set at least 180 s or by definition our time-out should be really small?  What do you think @m1ci ?

We can also set a [connection timeout](https://github.com/freme-project/freme-ner/blob/f18433c62e87aa67e5aca272d3686926b6895f05/src/main/scala/org/elinker/core/api/process/EntityLinker.scala#L41) for Solr and catch  related exceptions as you suggested - Today is unlimited.

Best,

**Comment by jnehring** [comment]
I am not sure. Lets discuss this on the next call. What is the current setting of the timeout?

**Comment by jnehring** [comment]
The problem happened 32 times in the last 3 weeks on freme-live. But there were times when it happened more often. From the error message I think the time out is 30 seconds which is ok. But can you please return another exception with HTTP Status code 502 - "Bad Gateway" and an appropriate error message?

Just throw one of these exceptions, you can specify the error message and our exception handler will add the right status code: https://github.com/freme-project/FREMECommon/blob/master/src/main/java/eu/freme/common/exception/ExternalServiceFailedException.java

**Comment by sandroacoelho** [comment]
Hi @jnehring 

Message as requested has been implemented.

Best,

**Comment by jnehring** [comment]
Thank you! I cannot test the issue but from looking at the code I assume it is finished.
