### ISSUE TITLE
startup of 0.8-SNAPSHOT failed

### ISSUE THREAD

**Issue by sandroacoelho** [freme-project/freme-ner#124]
from @ArneBinder 

I had to return to freme-ner:0.7 because startup of 0.8-SNAPSHOT failed:

```
ERROR   2016-07-21 02:23:31,315 [main] org.springframework.boot.SpringApplication  - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fremeNerEnrichment': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.elinker.core.api.java.FremeNer org.elinker.core.rest.FremeNerEnrichment.fremeNer; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getFremeNer': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.elinker.core.api.java.Config org.elinker.core.api.java.FremeNer.config; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: java.lang.String org.elinker.core.api.java.Config.linkingMethod; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'freme.ner.linkingMethod' in string value "${freme.ner.linkingMethod}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1208)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:762)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:690)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:970)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:959)
	at eu.freme.common.starter.FREMEStarter.startPackageFromClasspath(FREMEStarter.java:32)
	at eu.freme.common.starter.FREMEStarter.main(FREMEStarter.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.elinker.core.api.java.FremeNer org.elinker.core.rest.FremeNerEnrichment.fremeNer; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getFremeNer': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.elinker.core.api.java.Config org.elinker.core.api.java.FremeNer.config; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: java.lang.String org.elinker.core.api.java.Config.linkingMethod; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'freme.ner.linkingMethod' in string value "${freme.ner.linkingMethod}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 23 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getFremeNer': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.elinker.core.api.java.Config org.elinker.core.api.java.FremeNer.config; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: java.lang.String org.elinker.core.api.java.Config.linkingMethod; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'freme.ner.linkingMethod' in string value "${freme.ner.linkingMethod}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1208)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	... 25 more
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.elinker.core.api.java.Config org.elinker.core.api.java.FremeNer.config; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: java.lang.String org.elinker.core.api.java.Config.linkingMethod; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'freme.ner.linkingMethod' in string value "${freme.ner.linkingMethod}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 36 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: java.lang.String org.elinker.core.api.java.Config.linkingMethod; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'freme.ner.linkingMethod' in string value "${freme.ner.linkingMethod}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1208)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	... 38 more
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: java.lang.String org.elinker.core.api.java.Config.linkingMethod; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'freme.ner.linkingMethod' in string value "${freme.ner.linkingMethod}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 49 more
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'freme.ner.linkingMethod' in string value "${freme.ner.linkingMethod}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:174)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:204)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:178)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$2.resolveStringValue(PropertySourcesPlaceholderConfigurer.java:175)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:801)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:955)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
	... 51 more
```

Perhaps we should open another issue regarding this.

**Comment by jnehring** [comment]
What is the status here? I guess the bug is fixed but the parameter is not documented?

**Comment by sandroacoelho** [comment]
It's done.

**Comment by jnehring** [comment]
I cannot find the documentation.

**Comment by sandroacoelho** [comment]
Hi @jnehring ,

mmmm... I am lost. Newbies... sorry . For the documentation, I need open an issue with what we need to change or may I need to go further? What I need to do?

Thank you in advance,

**Comment by jnehring** [comment]
I think the implementation is ready and the documentation will be done in https://github.com/freme-project/Documentation/issues/270 . When this is true I think we can close this issue.

**Comment by sandroacoelho** [comment]
[Issue 270](freme-project/freme-project.github.io#270) has closed. So we can close this issue too.
