### ISSUE TITLE
Not a valid token for an RDF term

### ISSUE THREAD

**Issue by sandroacoelho** [freme-project/freme-ner#140]
```
er_1       | ERROR   2016-08-18 21:39:16,151 [http-nio-7002-exec-1] eu.freme.common.exception.ExceptionHandlerService  - Request: http://localhost:7002/e-entity/freme-ner/datasets/viaf raised 
ner_1       | eu.freme.common.exception.FREMEHttpException: [line: 15783, col: 59] Not a valid token for an RDF term: [GT]
ner_1       | 	at eu.freme.common.rest.OwnedResourceManagingController.putEntityById(OwnedResourceManagingController.java:222)
ner_1       | 	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
ner_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ner_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
ner_1       | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
ner_1       | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
ner_1       | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
ner_1       | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:775)
ner_1       | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
ner_1       | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
ner_1       | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
ner_1       | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
ner_1       | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:965)
ner_1       | 	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:878)
ner_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:651)
ner_1       | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:841)
ner_1       | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
ner_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
ner_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
ner_1       | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
ner_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
ner_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
ner_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
ner_1       | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
ner_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
ner_1       | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
ner_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
ner_1       | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
ner_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
ner_1       | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
ner_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
ner_1       | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
ner_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
ner_1       | 	at eu.freme.common.security.ManagementEndpointAuthenticationFilter.doFilter(ManagementEndpointAuthenticationFilter.java:83)
ner_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
ner_1       | 	at eu.freme.common.security.AuthenticationFilter.doFilter(AuthenticationFilter.java:92)
ner_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
ner_1       | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
ner_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
ner_1       | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:57)
ner_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ner_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
ner_1       | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
ner_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
ner_1       | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
ner_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ner_1       | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
ner_1       | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
ner_1       | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
ner_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
ner_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
ner_1       | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
ner_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ner_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
ner_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
ner_1       | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
ner_1       | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
ner_1       | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
ner_1       | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
ner_1       | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
ner_1       | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
ner_1       | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
ner_1       | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
ner_1       | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
ner_1       | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
ner_1       | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
ner_1       | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
ner_1       | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
ner_1       | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
ner_1       | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
ner_1       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
ner_1       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
ner_1       | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
ner_1       | 	at java.lang.Thread.run(Thread.java:745)





```

**Comment by jnehring** [comment]
I assume this is a bug? When does it happen and what are its consequences?

**Comment by sandroacoelho** [comment]
Hi @jnehring:

I opened this issue just to investigate if it is a bug or my file has a wrong format. I figure out that was a wrong format.

Best,
