### ISSUE TITLE
text causing FREME NER to fail process a document

### ISSUE THREAD

**Issue by m1ci** [freme-project/freme-ner#74]
Following request doesn't work:

`curl -v "http://rv2622.1blu.de:8081/api/entities?dataset=cordis-fp7&language=en&linkingMethod=SurfaceFormSimilarity1" -d @abstract.txt -H "Content-Type: text/plain; charset=UTF-8"`

where the document is [abstract.txt](https://github.com/freme-project/freme-ner/files/126167/abstract.txt)

If the last word "Latvia" is removed then it works. Weird.

The log of FREME NER shows:

``
[ERROR] [02/11/2016 11:19:55.828] [api-service-akka.actor.default-dispatcher-28] [akka://api-service/user/api/$zc/$a] None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:344)
	at scala.None$.get(Option.scala:342)
	at org.elinker.core.api.filter.SimilarityFilter.org$elinker$core$api$filter$SimilarityFilter$$computeSimilarity(SimilarityFilter.scala:44)
	at org.elinker.core.api.filter.SimilarityFilter$$anonfun$filterByStringSimilarity$1.apply(SimilarityFilter.scala:33)
	at org.elinker.core.api.filter.SimilarityFilter$$anonfun$filterByStringSimilarity$1.apply(SimilarityFilter.scala:33)
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1195)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at org.elinker.core.api.filter.SimilarityFilter.filterByStringSimilarity(SimilarityFilter.scala:33)
	at org.elinker.core.api.process.EntityLinker$$anonfun$receive$1$$anonfun$8.apply(EntityLinker.scala:186)
	at org.elinker.core.api.process.EntityLinker$$anonfun$receive$1$$anonfun$8.apply(EntityLinker.scala:186)
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at org.elinker.core.api.process.EntityLinker$$anonfun$receive$1.applyOrElse(EntityLinker.scala:186)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at org.elinker.core.api.process.EntityLinker.aroundReceive(EntityLinker.scala:29)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
``

**Comment by sandroacoelho** [comment]
I am investigating why the surface forms is arriving empty/none.  Seems to be related with timeouts.

**Comment by sandroacoelho** [comment]
Bug fixed
